#!/bin/bash

# run veilid

cd $(dirname $0); set -xe

#docker volume rm aws-cli
docker volume create aws-cli
docker rm -f aws-cli || true
docker run --rm -it --env-file env.sh -v aws-cli:/root/.aws/ --name aws-cli aws-cli:latest $@
