#!/bin/bash

# run veilid

cd $(dirname $0); set -xe

bash build.sh >/dev/null 2>&1

#docker volume rm aws-cli
docker volume create aws-cli
docker rm -f aws-cli || true
docker run --rm -it --env-file env.sh -v aws-cli:/root/.aws/ --name aws-cli aws-cli:latest $@

exit 0

# describe clusters
aws ecs describe-clusters \
    --cluster $cluster     

# describe task
aws ecs describe-tasks \
    --cluster $cluster \
    --tasks $task | grep enableExecuteCommand

# enable container exec
aws ecs update-service \
  --cluster $cluster \
  --service $service \
  --task-definition $task_definition \
  --force-new-deployment \
  --enable-execute-command

# disable container exec
aws ecs update-service \
  --cluster $cluster \
  --service $service \
  --task-definition $task_definition \
  --force-new-deployment \
  --disable-execute-command

# container exec
aws ecs execute-command \
    --cluster $cluster \
    --task $task \
    --container $container \
    --interactive \
    --command "/bin/bash"

# exec checker
bash <( curl -Ls https://raw.githubusercontent.com/aws-containers/amazon-ecs-exec-checker/main/check-ecs-exec.sh ) $cluster $task
